# etc/logging.conf
# Alle Logs (auch von Bibliotheken) landen über den Root-Logger in einer Datei.
[loggers]
keys=root,heizung

[logger_heizung]
level=INFO
handlers=
qualname=heizung
propagate=1

[logger_root]
level=INFO
handlers=file

[formatters]
keys=standardFormatter

[formatter_standardFormatter]
format=%(asctime)s.%(msecs)03d  %(levelname)-6s %(message)s
datefmt=%y-%m-%d %H:%M:%S

[handlers]
keys=file

[handler_file]
class=handlers.TimedRotatingFileHandler
formatter=standardFormatter
args=("/var/log/heizung/heizung.log","midnight",1,14)
