{
 "title": "Heizung UVR1611",
 "tags": [ "heizung" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pufferspeicher",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "last_over_time(aussentemperatur[5m])"
    },
    { "expr": "last_over_time(raum_rasp[5m])" },
    {
     "expr": "last_over_time(speicher_1_kopf[5m])"
    },
    {
     "expr": "last_over_time(speicher_2_kopf[5m])"
    },
    {
     "expr": "last_over_time(speicher_3_kopf[5m])"
    },
    {
     "expr": "last_over_time(speicher_4_mitte[5m])"
    },
    {
     "expr": "last_over_time(speicher_5_boden[5m])"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "last_over_time(solar_strahlung[5m])",
     "legendFormat": "Solarstrahlung"
    },
    { "expr": "last_over_time(solar_vl[5m])", "legendFormat": "VL Solar" },
    {
     "expr": "last_over_time(solar_ladepumpe_drehzahl[5m])",
     "legendFormat": "Drehzahl Ladepumpe Solar"
    }
   ]
  },
  {
   "title": "Heizung",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "last_over_time(heizung_vl[5m])", "legendFormat": "VL Heizung" },
    { "expr": "last_over_time(heizung_rl[5m])", "legendFormat": "RL Heizung" },
    {
     "expr": "last_over_time(heizung_pumpe_drehzahl[5m])",
     "legendFormat": "Drehzahl Heizungspumpe"
    }
   ]
  },
  {
   "title": "Wärmeerzeuger",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "last_over_time(kessel_rl[5m])", "legendFormat": "RL Kessel" },
    {
     "expr": "last_over_time(kessel_ladepumpe_drehzahl[5m])",
     "legendFormat": "Drehzahl Ladepumpe Kessel"
    },
    {
     "expr": "last_over_time(kessel_betriebstemperatur[5m])",
     "legendFormat": "Kessel Betriebstemperatur"
    },
    {
     "expr": "last_over_time(speicher_ladeleitung[5m])",
     "legendFormat": "Speicherladeleitung"
    }
   ]
  },
  {
   "title": "Digitale Ausgänge (0/1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "boolean" } },
   "targets": [
    { "expr": "last_over_time(heizung_an[5m])", "legendFormat": "Heizung An" },
    {
     "expr": "last_over_time(d_heizung_pumpe[5m])",
     "legendFormat": "Heizung Pumpe"
    },
    {
     "expr": "last_over_time(d_kessel_ladepumpe[5m])",
     "legendFormat": "Kessel Ladepumpe"
    },
    {
     "expr": "last_over_time(d_kessel_freigabe[5m])",
     "legendFormat": "Kessel Freigabe"
    },
    {
     "expr": "last_over_time(d_heizung_mischer_auf[5m])",
     "legendFormat": "Hz Mischer auf"
    },
    {
     "expr": "last_over_time(d_heizung_mischer_zu[5m])",
     "legendFormat": "Hz Mischer zu"
    },
    {
     "expr": "last_over_time(d_kessel_mischer_auf[5m])",
     "legendFormat": "Kessel Mischer auf"
    },
    {
     "expr": "last_over_time(d_kessel_mischer_zu[5m])",
     "legendFormat": "Kessel Mischer zu"
    },
    {
     "expr": "last_over_time(d_solar_kreispumpe[5m])",
     "legendFormat": "Solarkreispumpe"
    },
    {
     "expr": "last_over_time(d_solar_ladepumpe[5m])",
     "legendFormat": "Solar Ladepumpe"
    },
    {
     "expr": "last_over_time(d_solar_freigabepumpe[5m])",
     "legendFormat": "Solar Freigabepumpe"
    }
   ]
  }
 ]
}